### ISSUE TITLE
Invisible entities showing

### ISSUE THREAD

**Issue by Ulrar** [xBourner/status-card#3]
Hi,

It seems entities with 'visible' disabled seems to still be showing through this card, is there a way to hide them ?

It means it shows light groups as well as each light in the group, making the light menu (and presumably other domains) a bit confusing.

Thanks

**Comment by Ulrar** [comment]
Sure, I keep the group visible and mark the members non visible so it'll work.
I can't outright disable the entities because powercalc needs them, but the visible toggle is perfect for this.

Thanks!

**Comment by xBourner** [comment]
Hi, i added this feature with the latest release. It won't render, when you enable/disable visibility of an entity out of the card. 
You have to reload the site so it will show or not show the (non) visible entity. Entities which was non visible before should'nt be shown in the card.

**Comment by Ulrar** [comment]
Seems to work perfectly, thanks so much !
