### ISSUE TITLE
Status-Card empty

### ISSUE THREAD

**Issue by uwalcher** [xBourner/status-card#4]
Hi
On default my status-card is empty. Entries are only visible, when I add "showPerson:" in Yaml-Code. 

![image](https://github.com/user-attachments/assets/132d0f10-e0ba-4644-af8e-5f7de9d565fa)

But still without Persons.

type: custom:status-card
showPerson:

![image](https://github.com/user-attachments/assets/224fe36b-4d00-4acb-866a-605286fbbb5e)

**Comment by xBourner** [comment]
is the graphical editor not visible for you?
showPerson: true would be correct

**Comment by uwalcher** [comment]
Graphical editor is visible, but all empty in the beginning. 
![image](https://github.com/user-attachments/assets/e8c8f652-ebbd-46fc-9362-e623b5213f35)


Only with the entry showPerson: is something on the card. 
![image](https://github.com/user-attachments/assets/2b8875f8-1364-4996-b5ec-40ee32d9f4f2)


When I use "showPerson: true", the card is empty again.

![image](https://github.com/user-attachments/assets/19c33538-f59f-480d-a03f-8803d3ca3f32)

Version:
![image](https://github.com/user-attachments/assets/9ab074bd-068e-4f32-bc45-bb4a4be574df)

**Comment by xBourner** [comment]
hmm i have the exact same versions like you. I'm not sure why it behaves like this. 
what happens when you add:

```
type: custom:dev-status-card
extra_entities:
  - entity: ""
    status: ""
    icon: ""
    color: ""
```
  
  seems like the card wants some input. it looks the card would work. 
also any errors in console? (Browser Dev Tools [F12])

**Comment by uwalcher** [comment]
Stays empty..
![image](https://github.com/user-attachments/assets/e6514b8e-4bab-4f18-bb48-2fd07bce6625)

![image](https://github.com/user-attachments/assets/7666ad4d-1070-4cc3-90c2-12326366a79b)

**Comment by xBourner** [comment]
added from another issue:

in which way you installed HA?

HA OS, Container, Core, Supervised?
Also on which hardware? maybe i can build this as a test environment to reproduce it

also could you try my new verison if anything is different?

**Comment by uwalcher** [comment]
Version 2.1.1 installed, same behavior.
Could it be, that's something wrong with the parameters? When I add showPerson in Yaml and go back to Gui-Editor and disable Person, afterwards I see this in Yaml.

![image](https://github.com/user-attachments/assets/444d5fa2-8763-495c-bd6c-96a60ed0a2ce)

I have HA OS installed on a proxmox vm.

**Comment by xBourner** [comment]
hmm thats crazy. 
i have also HA OS on proxmox. for me (and i think for many more people) it works as expected. 

when you only add:

`type: custom:status-card`

it should already show persons and also domains (when entities have state on) 

what happens when you have the code?

`type: custom:dev-status-card
showPerson: false`

also what language do you use and does your name has any special characters?

**Comment by uwalcher** [comment]
Hi 

I use english any my name is urs (nothing special)

The only thing what is different. My HA is located in SouthAfrica and I use a Cloudflare-Tunnel to connect. I will check it from a local workstation.

![image](https://github.com/user-attachments/assets/4a059e1e-2a5c-41b5-b835-e83103ad2705)


type: custom:status-card

![image](https://github.com/user-attachments/assets/402f5b25-39ec-4d16-a430-b5e9f7c0450f)

type: custom:dev-status-card
showPerson: false

![image](https://github.com/user-attachments/assets/ed2a129f-b878-4851-b01b-454f7d812c2a)

**Comment by uwalcher** [comment]
Hi
I have Dwains Dashboard installed too and there I see the users.
![image](https://github.com/user-attachments/assets/2599b4f8-c367-4b35-ad30-344cd5d824ba)

**Comment by xBourner** [comment]
could you send me some screenshots from dev console when you open the card and when you open the editor?

i will send you my "dev-status-card" so we can see where the exact error is. but i need to set this up at first and enable some debugging where your error happens

**Comment by uwalcher** [comment]
Evt. it helps:
This is happen, when I try to enable "Show Person Enities" in GUI.
![image](https://github.com/user-attachments/assets/3c4244b7-868a-45c5-b44b-6d603cae6ac6)

And this, when I edit the entry "ShowPerson" in yaml (from false to true).

![image](https://github.com/user-attachments/assets/a442f393-491f-4c78-80e5-955022c51100)

Thanks!!

**Comment by uwalcher** [comment]
Hi 

I installed the status-card on my local Installation (not in SA over cloudflare Tunnel). And there it works fine. I guess there is something wrong with the Person-entities. I will try to fix it, but I don't think it's a card problem. Let's close this issue, I keep you informed. 

Thank you very much for your support and patience.....

Urs 

Picture from my local Inst. :
![image](https://github.com/user-attachments/assets/26512294-4fb5-4d6b-b374-68dfee3305bc)

**Comment by xBourner** [comment]
Okay. Feel free to open this again or a new one if you need help.

**Comment by uwalcher** [comment]
Thanks!!!

**Comment by xBourner** [comment]
Please check v2.2.0 (latest release). It should fix the behavior. The card should work if you have all persons enabled, or some hidden or non visible.

**Comment by xBourner** [comment]
Is it working for you now?

**Comment by uwalcher** [comment]
Hi
Sorry for the delay.
Yes, the Problem with the users seems to be solved. But I have this problem too:

Problems with the visual editor #14

Thanks, Urs

**Comment by xBourner** [comment]
Thank you for the answer. I will close this issue for now. I hope i can get more info about the issues in https://github.com/xBourner/status-card/issues/14
