### ISSUE TITLE
Card can only display full name

### ISSUE THREAD

**Issue by Esp32-zapper** [xBourner/status-card#6]
Hi!
First of all, tnx gor a great card. Used Dwain's dash for years so this is something I've been missing when I play with the default HA dash.
However, in Dwain's only the first (Christian) name is displayed and that makes the the card a bit more compact. A family of 4 will not fit if you don't make the section extra wide. I can't find a setting for "short" name nighter in gui or yaml.
A setting to choose full name, short name or no name would be great. In a family, the picture is often enough.

Tnx again!

**Comment by xBourner** [comment]
So you have your first and last name set in HA as your persons name?
I only have my first name so it only shows this. I never thought of this. And i dont believe anyone wants the last name in the status card. So i will change this. 

Not sure if i will add a toggle to completely hide the name of persons. 
I will put this on my list (maybe takes some time)

**Comment by Esp32-zapper** [comment]
Time is only an illusion and lunch time double so, as the hitchhiker taught us, so no problem.

Tnx!

**Comment by xBourner** [comment]
good news to this. i had some time to do it and i almost finished it. 
Will cut the name to the first space so only the first name will show in the card. 

also added a toggle which will hide person name. will look into other issues and release a new version later (maybe tomorrow)

**Comment by Esp32-zapper** [comment]
Could take some time, right? 🤣

**Comment by xBourner** [comment]
> Could take some time, right? 🤣

It depends if i have some spare time, or not :D
I published a new release and also added the toggle to hide person names. 

as an extra i added a toggle to hide domain names. this will also hide names for device_classes and also for extra entities.

please give me some feedback if you like it :)

**Comment by Esp32-zapper** [comment]
Tested!
Works just fine.
Maybe you should consider having a bit lager minimum spacing between persons.
Now the length of the name will control it but if you have a household consisting of 4 persons John, Alexandra, Max & Lisa, Alexandra will look like she is in a separate category as there will be a much bigger spacing around her name.
This is a VERY minor thing. Just my OCD playing tricks on me, I suppose.🤣

**Comment by xBourner** [comment]
Yeah it looks a bit off when names are longer in width than the width of the picture/icon. same for domains.
Im not sure how to do that because adding more space will result in other issues. changing width would result in non readable names. adding extra space would make the card wider and shows less info. 

i will leave it like this at the moment

**Comment by Esp32-zapper** [comment]
Yes, it's a balancing act. Better leave it as is.
For me, the change you did today was spot on. Really like it!

**Comment by Esp32-zapper** [comment]
That you can limit content by excluding persons and limit by room is brilliant.
As I'm used to Dwain's, I kind of used to structure by room and this is perfect as a room header. Rooms that doesn't "belong" to anyone has just the device summary.
![Screenshot_20241115-184426](https://github.com/user-attachments/assets/3aafcb6a-0023-43cd-980f-2b9d29bba5ae)

Brilliant!
